# Generated by Django 4.0.4 on 2022-04-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_sale_sold_alter_sale_total_alter_saleline_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
