# Generated by Django 4.0.4 on 2022-04-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_sale_total_alter_saleline_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
